-- Align live LOTS to CSV column names; keep row values.
-- Child FKs (ANALYSIS_LOTS / ISSUES / HANDOVER_HISTORY).lot_id → LOTS(id).
-- ID string values unchanged (e.g. LOT-…, ISS-yyMMdd-###).

SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE ANALYSIS_LOTS DROP FOREIGN KEY fk_analysis_lots_lot;
ALTER TABLE ISSUES DROP FOREIGN KEY fk_issues_lot;
ALTER TABLE HANDOVER_HISTORY DROP FOREIGN KEY fk_handover_lot;

ALTER TABLE LOTS DROP COLUMN IF EXISTS imported_at;
ALTER TABLE LOTS CHANGE COLUMN lot_id id VARCHAR(64) NOT NULL;
ALTER TABLE LOTS CHANGE COLUMN recorded_at `timestamp` DATETIME NOT NULL;
ALTER TABLE LOTS DROP COLUMN IF EXISTS residual_li;

ALTER TABLE ANALYSIS_LOTS
  ADD CONSTRAINT fk_analysis_lots_lot
  FOREIGN KEY (lot_id) REFERENCES LOTS(id)
  ON DELETE CASCADE;

ALTER TABLE ISSUES
  ADD CONSTRAINT fk_issues_lot
  FOREIGN KEY (lot_id) REFERENCES LOTS(id);

ALTER TABLE HANDOVER_HISTORY
  ADD CONSTRAINT fk_handover_lot
  FOREIGN KEY (lot_id) REFERENCES LOTS(id);

SET FOREIGN_KEY_CHECKS = 1;
