-- Decouple HANDOVER_HISTORY from ISSUES (2026-08-08).
-- Prefer: npm run migrate:handover-decouple-ISSUES

ALTER TABLE HANDOVER_HISTORY DROP FOREIGN KEY fk_handover_issue;
ALTER TABLE HANDOVER_HISTORY DROP INDEX IF EXISTS idx_handover_issue;
ALTER TABLE HANDOVER_HISTORY DROP COLUMN IF EXISTS issue_id;
